# Generated by Django 3.1 on 2020-09-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200906_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='child_default.png', null=True, upload_to='avatar'),
        ),
    ]
